/**
 * The 2026 regular season as the league's own sheet records it, transcribed from
 * section 6.5 of `docs/knowledge-base.md`. Test fixture only: the versioned seed
 * the site falls back on is generated by the importer in a later phase.
 *
 * It holds rounds 1 to 5 plus the 6th-versus-7th play-in, which is what the
 * published 4 July 2026 standings cover. The playoff rounds are left out because
 * their participants were still undetermined when the sheet was handed over.
 *
 * Two rows are kept deliberately awkward, because the source is:
 *
 * - round 1 carries a match with a time and a venue and no teams;
 * - round 5 leaves the "Resultado" and "Ganador" columns empty on its last four
 *   matches. The goals are the reliable part, and every one of those matches was
 *   decided by more than a goal, so they are transcribed as regulation results.
 *   The published PGR column agrees: it accounts for exactly two shootout wins
 *   all season, both in earlier rounds.
 */

import type {
  CompetitionKey,
  Match,
  MatchResolution,
  MatchStage,
  Venue,
} from '../../data/types'

export const BEER_TEAMS = [
  'birra-del-fuego',
  'blanco',
  'rock-choppers',
  'short-shift-soft-sticks',
  'sucucho',
  'tipo-nine',
  'zhockey',
] as const

export const WUBL_TEAMS = [
  'wubl-birra-del-fuego',
  'wubl-sucucho',
  'wubl-tipo-nine',
  'wubl-zhockey',
] as const

interface Row {
  date: string
  time: string
  venue: Venue
  competition: CompetitionKey
  home: string | null
  away: string | null
  goals: [number, number] | null
  resolution?: MatchResolution
  stage?: MatchStage
}

const ROWS: readonly Row[] = [
  // Round 1, Saturday 23 May 2026.
  {
    date: '2026-05-23',
    time: '21:30',
    venue: 'bahia',
    competition: 'beer',
    home: null,
    away: null,
    goals: null,
  },
  {
    date: '2026-05-23',
    time: '21:30',
    venue: 'poli',
    competition: 'beer',
    home: 'rock-choppers',
    away: 'sucucho',
    goals: [9, 6],
  },
  {
    date: '2026-05-23',
    time: '22:30',
    venue: 'bahia',
    competition: 'beer',
    home: 'short-shift-soft-sticks',
    away: 'blanco',
    goals: [5, 4],
    resolution: 'shootout',
  },
  {
    date: '2026-05-23',
    time: '22:30',
    venue: 'poli',
    competition: 'beer',
    home: 'zhockey',
    away: 'birra-del-fuego',
    goals: [6, 14],
  },
  {
    date: '2026-05-23',
    time: '23:30',
    venue: 'bahia',
    competition: 'beer',
    home: 'rock-choppers',
    away: 'birra-del-fuego',
    goals: [8, 11],
  },
  {
    date: '2026-05-23',
    time: '23:30',
    venue: 'poli',
    competition: 'beer',
    home: 'zhockey',
    away: 'sucucho',
    goals: [6, 3],
  },

  // Round 2, Saturday 30 May 2026.
  {
    date: '2026-05-30',
    time: '21:30',
    venue: 'bahia',
    competition: 'beer',
    home: 'sucucho',
    away: 'tipo-nine',
    goals: [10, 3],
  },
  {
    date: '2026-05-30',
    time: '21:30',
    venue: 'poli',
    competition: 'beer',
    home: 'blanco',
    away: 'birra-del-fuego',
    goals: [7, 8],
    resolution: 'shootout',
  },
  {
    date: '2026-05-30',
    time: '22:30',
    venue: 'bahia',
    competition: 'beer',
    home: 'short-shift-soft-sticks',
    away: 'rock-choppers',
    goals: [9, 6],
  },
  {
    date: '2026-05-30',
    time: '22:30',
    venue: 'poli',
    competition: 'beer',
    home: 'sucucho',
    away: 'blanco',
    goals: [4, 3],
  },
  {
    date: '2026-05-30',
    time: '23:30',
    venue: 'bahia',
    competition: 'beer',
    home: 'zhockey',
    away: 'tipo-nine',
    goals: [6, 8],
  },
  {
    date: '2026-05-30',
    time: '23:30',
    venue: 'poli',
    competition: 'beer',
    home: 'short-shift-soft-sticks',
    away: 'birra-del-fuego',
    goals: [2, 5],
  },

  // Round 3, Saturday 6 June 2026, the first women's round.
  {
    date: '2026-06-06',
    time: '21:30',
    venue: 'bahia',
    competition: 'wubl',
    home: 'wubl-zhockey',
    away: 'wubl-tipo-nine',
    goals: [3, 5],
  },
  {
    date: '2026-06-06',
    time: '21:30',
    venue: 'poli',
    competition: 'wubl',
    home: 'wubl-birra-del-fuego',
    away: 'wubl-sucucho',
    goals: [2, 3],
  },
  {
    date: '2026-06-06',
    time: '22:30',
    venue: 'bahia',
    competition: 'beer',
    home: 'zhockey',
    away: 'short-shift-soft-sticks',
    goals: [5, 9],
  },
  {
    date: '2026-06-06',
    time: '22:30',
    venue: 'poli',
    competition: 'beer',
    home: 'rock-choppers',
    away: 'tipo-nine',
    goals: [4, 10],
  },
  {
    date: '2026-06-06',
    time: '23:30',
    venue: 'bahia',
    competition: 'wubl',
    home: 'wubl-zhockey',
    away: 'wubl-birra-del-fuego',
    goals: [6, 7],
  },
  {
    date: '2026-06-06',
    time: '23:30',
    venue: 'poli',
    competition: 'wubl',
    home: 'wubl-sucucho',
    away: 'wubl-tipo-nine',
    goals: [4, 1],
  },

  // Round 4, Sunday 28 June 2026. The women's 4-4 is the draw on record.
  {
    date: '2026-06-28',
    time: '21:30',
    venue: 'bahia',
    competition: 'beer',
    home: 'zhockey',
    away: 'rock-choppers',
    goals: [7, 9],
  },
  {
    date: '2026-06-28',
    time: '21:30',
    venue: 'poli',
    competition: 'beer',
    home: 'tipo-nine',
    away: 'birra-del-fuego',
    goals: [6, 7],
  },
  {
    date: '2026-06-28',
    time: '22:30',
    venue: 'bahia',
    competition: 'wubl',
    home: 'wubl-birra-del-fuego',
    away: 'wubl-tipo-nine',
    goals: [4, 4],
    resolution: 'draw',
  },
  {
    date: '2026-06-28',
    time: '22:30',
    venue: 'poli',
    competition: 'wubl',
    home: 'wubl-sucucho',
    away: 'wubl-zhockey',
    goals: [4, 2],
  },
  {
    date: '2026-06-28',
    time: '23:30',
    venue: 'bahia',
    competition: 'beer',
    home: 'sucucho',
    away: 'short-shift-soft-sticks',
    goals: [4, 9],
  },
  {
    date: '2026-06-28',
    time: '23:30',
    venue: 'poli',
    competition: 'beer',
    home: 'blanco',
    away: 'tipo-nine',
    goals: [10, 7],
  },

  // Round 5, Saturday 4 July 2026. The last row of the sheet is a bye and is
  // not a match, so it is not transcribed.
  {
    date: '2026-07-04',
    time: '21:30',
    venue: 'bahia',
    competition: 'beer',
    home: 'rock-choppers',
    away: 'blanco',
    goals: [8, 5],
  },
  {
    date: '2026-07-04',
    time: '21:30',
    venue: 'poli',
    competition: 'beer',
    home: 'sucucho',
    away: 'birra-del-fuego',
    goals: [3, 4],
  },
  {
    date: '2026-07-04',
    time: '22:30',
    venue: 'bahia',
    competition: 'beer',
    home: 'short-shift-soft-sticks',
    away: 'tipo-nine',
    goals: [6, 4],
  },
  {
    date: '2026-07-04',
    time: '22:30',
    venue: 'poli',
    competition: 'beer',
    home: 'zhockey',
    away: 'blanco',
    goals: [1, 8],
  },
  // The 6th-versus-7th play-in: the winner reaches the playoffs, and the league
  // does not count it as a seventh regular game.
  {
    date: '2026-07-04',
    time: '23:30',
    venue: 'bahia',
    competition: 'beer',
    home: 'tipo-nine',
    away: 'zhockey',
    goals: [10, 7],
    stage: 'playin',
  },
]

export const SEASON_2026_MATCHES: readonly Match[] = ROWS.map((row, index) => ({
  id: `2026-${String(index + 1).padStart(3, '0')}`,
  competition: row.competition,
  stage: row.stage ?? 'regular',
  date: row.date,
  time: row.time,
  venue: row.venue,
  homeTeamId: row.home,
  awayTeamId: row.away,
  score: row.goals
    ? {
        home: row.goals[0],
        away: row.goals[1],
        resolution: row.resolution ?? 'regulation',
      }
    : null,
  notes: null,
}))

/**
 * The Beer League table the league published on 4 July 2026, section 6.4.
 *
 * One cell is not reproducible and is corrected here: Blanco is published with
 * PP 1, which contradicts the same row's PJ 6, since 2 wins plus 1 loss plus 2
 * shootout losses is five games. Its points, goals and goal difference all
 * reconcile, so the loss column is a slip on the sheet and the value below is
 * the one the results give. Everything else matches cell for cell.
 */
export const PUBLISHED_BEER_STANDINGS = [
  {
    teamId: 'birra-del-fuego',
    points: 12,
    wins: 6,
    losses: 0,
    shootoutLosses: 0,
    regulationWins: 5,
    goalsFor: 49,
    goalsAgainst: 32,
    goalDifference: 17,
    played: 6,
    draws: 0,
  },
  {
    teamId: 'short-shift-soft-sticks',
    points: 10,
    wins: 5,
    losses: 1,
    shootoutLosses: 0,
    regulationWins: 4,
    goalsFor: 40,
    goalsAgainst: 28,
    goalDifference: 12,
    played: 6,
    draws: 0,
  },
  {
    teamId: 'rock-choppers',
    points: 6,
    wins: 3,
    losses: 3,
    shootoutLosses: 0,
    regulationWins: 3,
    goalsFor: 44,
    goalsAgainst: 48,
    goalDifference: -4,
    played: 6,
    draws: 0,
  },
  {
    teamId: 'blanco',
    points: 6,
    wins: 2,
    losses: 2,
    shootoutLosses: 2,
    regulationWins: 2,
    goalsFor: 37,
    goalsAgainst: 33,
    goalDifference: 4,
    played: 6,
    draws: 0,
  },
  {
    teamId: 'sucucho',
    points: 4,
    wins: 2,
    losses: 4,
    shootoutLosses: 0,
    regulationWins: 2,
    goalsFor: 30,
    goalsAgainst: 34,
    goalDifference: -4,
    played: 6,
    draws: 0,
  },
  {
    teamId: 'tipo-nine',
    points: 4,
    wins: 2,
    losses: 4,
    shootoutLosses: 0,
    regulationWins: 2,
    goalsFor: 38,
    goalsAgainst: 43,
    goalDifference: -5,
    played: 6,
    draws: 0,
  },
  {
    teamId: 'zhockey',
    points: 2,
    wins: 1,
    losses: 5,
    shootoutLosses: 0,
    regulationWins: 1,
    goalsFor: 31,
    goalsAgainst: 51,
    goalDifference: -20,
    played: 6,
    draws: 0,
  },
] as const

/** The Women's Beer League table of 4 July 2026, section 6.4. */
export const PUBLISHED_WUBL_STANDINGS = [
  {
    teamId: 'wubl-sucucho',
    points: 6,
    wins: 3,
    losses: 0,
    draws: 0,
    regulationWins: 3,
    goalsFor: 11,
    goalsAgainst: 5,
    goalDifference: 6,
    played: 3,
    shootoutLosses: 0,
  },
  {
    teamId: 'wubl-birra-del-fuego',
    points: 3,
    wins: 1,
    losses: 1,
    draws: 1,
    regulationWins: 1,
    goalsFor: 13,
    goalsAgainst: 13,
    goalDifference: 0,
    played: 3,
    shootoutLosses: 0,
  },
  {
    teamId: 'wubl-tipo-nine',
    points: 3,
    wins: 1,
    losses: 1,
    draws: 1,
    regulationWins: 1,
    goalsFor: 10,
    goalsAgainst: 11,
    goalDifference: -1,
    played: 3,
    shootoutLosses: 0,
  },
  {
    teamId: 'wubl-zhockey',
    points: 0,
    wins: 0,
    losses: 3,
    draws: 0,
    regulationWins: 0,
    goalsFor: 11,
    goalsAgainst: 16,
    goalDifference: -5,
    played: 3,
    shootoutLosses: 0,
  },
] as const

/**
 * The goalkeeper rows the league published, sections 6.7 and 6.9, with the
 * percentage exactly as printed. All eleven reconcile with shots faced and goals
 * against, which is what pins the formula down.
 */
export const PUBLISHED_GOALKEEPERS = [
  {
    playerId: 'badaracco-nico',
    shotsFaced: 173,
    goalsAgainst: 25,
    printed: 86,
  },
  {
    playerId: 'amaolo-lanata-gonza',
    shotsFaced: 84,
    goalsAgainst: 10,
    printed: 88,
  },
  { playerId: 'zayas-marcelo', shotsFaced: 156, goalsAgainst: 32, printed: 79 },
  {
    playerId: 'bernales-joaquin',
    shotsFaced: 151,
    goalsAgainst: 32,
    printed: 79,
  },
  {
    playerId: 'lopez-mieres-martin',
    shotsFaced: 84,
    goalsAgainst: 23,
    printed: 73,
  },
  {
    playerId: 'zunino-francisco',
    shotsFaced: 121,
    goalsAgainst: 35,
    printed: 71,
  },
  {
    playerId: 'valdez-gustavo',
    shotsFaced: 185,
    goalsAgainst: 57,
    printed: 69,
  },
  {
    playerId: 'amaolo-lanata-eugenia',
    shotsFaced: 134,
    goalsAgainst: 52,
    printed: 61,
  },
  { playerId: 'jofre-lautaro', shotsFaced: 46, goalsAgainst: 19, printed: 59 },
  {
    playerId: 'wubl-amaolo-lanata-eugenia',
    shotsFaced: 39,
    goalsAgainst: 8,
    printed: 79,
  },
  {
    playerId: 'cavaliere-milagros',
    shotsFaced: 54,
    goalsAgainst: 16,
    printed: 70,
  },
] as const
