/**
 * The shape of a versioned season snapshot.
 *
 * The site has to render when Supabase is unreachable. The free tier pauses a
 * project after about a week of inactivity and this league plays every two to
 * four weeks, so an empty database is a normal state rather than an incident,
 * and the seed is what stands in for it.
 *
 * A seed is generated by `npm run build:seed` out of `docs/sources/` and is never
 * edited by hand: the generator reconciles what it read against the tables the
 * league published and refuses to write when they disagree, which is a guarantee
 * a hand edit would quietly remove.
 */

import type { TeamSeed } from './teams-2026'
import type { CompetitionKey, Match } from './types'

export interface SeedPlayer {
  slug: string
  /** Cased for display; the spelling is the sheet's. */
  name: string
  /** Exactly as the roster sheet types it, kept so a re-import can match. */
  printedName: string
}

export interface SeedRosterEntry {
  playerSlug: string
  teamSlug: string
  competition: CompetitionKey
  jerseyNumber: number | null
}

/**
 * One line of a table the league published, transcribed. Not an aggregate of our
 * own match records: the sources carry no per-goal record, so these totals are
 * the only scoring fact that exists for 2026. The site shows them as published
 * on a date, never merged into a derived table.
 */
export interface SeedPublishedPlayerLine {
  competition: CompetitionKey
  /** The file under `docs/sources/` this line was read from. */
  sourceFile: string
  printedPlayerName: string
  printedTeam: string | null
  playerSlug: string | null
  teamSlug: string | null
  /**
   * The player's name as the roster spells it, when the line was matched. The
   * site shows this and falls back to the printed text, so a truncated
   * "Beltrami Ramir" is only ever displayed when nothing better is known.
   */
  resolvedName: string | null
  assists: number
  goals: number
  points: number
}

export interface SeedPublishedGoalieLine {
  competition: CompetitionKey
  sourceFile: string
  printedPlayerName: string
  printedTeam: string | null
  playerSlug: string | null
  teamSlug: string | null
  resolvedName: string | null
  gamesPlayed: number
  shotsFaced: number
  goalsAgainst: number
  /**
   * There is deliberately no save percentage here, as there is none in
   * `goalie_lines`: it is `(shots - goals) / shots`, computed on read. The
   * percentage the sheet prints is checked against these two numbers while the
   * seed is built and then dropped, so it can never become a second answer.
   */
}

/**
 * Something the calendar reserves that is not a match: the all-star slots, which
 * name no teams and no competition, and the emergency date of 22 August.
 */
export interface SeedCalendarNote {
  date: string | null
  time: string | null
  printed: string
  reason: string
}

export interface Seed {
  season: number
  /** The date the league published the totals this snapshot carries. */
  publishedOn: string
  /** The files under `docs/sources/` this was read from. */
  sources: readonly string[]
  teams: readonly TeamSeed[]
  players: readonly SeedPlayer[]
  rosters: readonly SeedRosterEntry[]
  matches: readonly Match[]
  publishedPlayerStats: readonly SeedPublishedPlayerLine[]
  publishedGoalieStats: readonly SeedPublishedGoalieLine[]
  calendarNotes: readonly SeedCalendarNote[]
  /**
   * What the sources leave unresolved, carried into the application on purpose.
   * A gap the league has not answered is published as a gap; this is the list the
   * site can show and the organisation can work through.
   */
  findings: readonly string[]
}
